### ISSUE TITLE
[8.0][mrp_operations_extension] 'action_start_working' ignores the MO's workflow

### ISSUE THREAD

**Issue by zamberjo** [OCA/manufacture#102]
When you start a WO, it sets the MO state ignoring the MO workflow behaviour as you can see in this PR: (https://github.com/OCA/manufacture/commit/5e6ced1cd9b18855ce3f7ed2f1860d9f3ad4c1ae#diff-5ddfc0f2cd6e2a6524362393d297c9deR158)

This code isn't necessary at all  because the **modify_production_order_state** method (**mrp_operations**) changes the  state to **in_production** through the workflow: see https://github.com/odoo/odoo/blob/8.0/addons/mrp_operations/mrp_operations.py#L118

**Comment by zamberjo** [comment]
We've fixed it in our fork https://github.com/diagramsoftware/manufacture/commit/01c75aa18ad7a6e1ffbb5c02f30513746e84ee85, we can do a PR if you agree.

**Comment by pedrobaeza** [comment]
OK, make the PR and we discuss about it there (although I see at first sight as correct).

**Comment by LoisRForgeFlow** [comment]
Related PR has been merged.
