### ISSUE TITLE
Bug in mrp_subcontracting_partner_management: No qty_received when delivering from one subcontractor to another

### ISSUE THREAD

**Issue by david-fleischmann** [OCA/manufacture#1024]
I found a bug in Subcontracting Partner Management
## Module
mrp_subcontracting_partner_management

## Describe the bug
When I purchase subcontracted products from one subcontractor (1) to another one (2) (for further manufacturing) and receive the stock picking at subcontractor (2) by validating the purchase.order qty_received when is still 0 although received.
Found this in debugging, but doesn't make sense to me for subcontracting workflow:
![image](https://user-images.githubusercontent.com/73656049/235208782-c6c2cc3c-f8ff-4ed1-8c7e-e978e0bb197d.png)

## To Reproduce
**Affected versions**: 14 and 15

1. Make a Purchase of a Subcontracted Product to another Subcontractor
2. Receive The goods there
3. In purchase order qty_received is still 0

![image](https://user-images.githubusercontent.com/73656049/235206959-5f79eeed-836e-4d0f-aaa2-702e314ed6a0.png)
![image](https://user-images.githubusercontent.com/73656049/235207281-5b9115ab-3fbb-4c5b-8ae0-dc66f977613e.png)

**Expected behavior**
qty_received should be set according to the qty received in stock.picking
**Additional context**
With non subcontracting products it works perfectly

**Comment by francesco-ooops** [comment]
@david-fleischmann would you be able to open a PR to fix this behavior?

**Comment by david-fleischmann** [comment]
@francesco-ooops unfortunately i have no approach yet. Maybe I also understand it wrong, how do you deliver to your subcontractor from another vendor?

**Comment by elvise** [comment]
hey @david-fleischmann thanks for your feedback we will check it

**Comment by david-fleischmann** [comment]
> hey @david-fleischmann thanks for your feedback we will check it

@elvise thanks! :)

Those modules already helped a bit, since now it's considered as a dropship at least.:
https://github.com/OCA/stock-logistics-transport/tree/15.0
But still Received qty is 0. 
And I found out this problem only occurs when I'm delivering subcontracted goods from one SubC to another. For non subcontracted goods it will set the qty as received.
![image](https://github.com/OCA/manufacture/assets/73656049/458425d7-9fc9-4238-9245-6f42bc181c7a)

**Comment by elvise** [comment]
hey @david-fleischmann ! 
i’m studying this case, have you tested in the [odoo V14 runbot](https://runbot.odoo.com/runbot) ?

**Comment by david-fleischmann** [comment]
@elvise 
Yes, just did on http://oca-manufacture-14-0-f2092617ca99.runboat.odoo-community.org/:
BOM Subcontracted at sub1
![image](https://github.com/OCA/manufacture/assets/73656049/f70eb82e-e28d-4d52-87f8-8beaa76b4f45)

PO Ordered at Sub1 Delivered to Sub2 and Received but qty received stays zero:
![image](https://github.com/OCA/manufacture/assets/73656049/c85402d0-a3eb-42bc-bf2d-561829808ed7)
![image](https://github.com/OCA/manufacture/assets/73656049/77644353-6384-41a2-a2c8-58290f82d694)

Receipt:
![image](https://github.com/OCA/manufacture/assets/73656049/d6c09e15-f2bb-45d2-9f5a-f96bf68131cb)

**Comment by elvise** [comment]
> @elvise Yes, just did on http://oca-manufacture-14-0-f2092617ca99.runboat.odoo-community.org/: BOM Subcontracted at sub1 ![image](https://user-images.githubusercontent.com/73656049/242910038-f70eb82e-e28d-4d52-87f8-8beaa76b4f45.png)
> 
> PO Ordered at Sub1 Delivered to Sub2 and Received but qty received stays zero: ![image](https://user-images.githubusercontent.com/73656049/242910407-c85402d0-a3eb-42bc-bf2d-561829808ed7.png) ![image](https://user-images.githubusercontent.com/73656049/242910528-77644353-6384-41a2-a2c8-58290f82d694.png)
> 
> Receipt: ![image](https://user-images.githubusercontent.com/73656049/242910730-d6c09e15-f2bb-45d2-9f5a-f96bf68131cb.png)

Hi @david-fleischmann thanks for the reply, to test the standard behavior of odoo you have to run the tests in the odoo v14 runbot.

**Comment by david-fleischmann** [comment]
@elvise I did (on OCA runbot, bc there are the affected modules), as I wrote in first line:
http://oca-manufacture-14-0-f2092617ca99.runboat.odoo-community.org/:

**Comment by elvise** [comment]
@david-fleischmann this is not the Odoo runbot but it's the OCA runbot, this is the of the [Odoo Runbot ](https://runbot.odoo.com/runbot) 

(Need to test the standard behaviour)

**Comment by david-fleischmann** [comment]
@elvise In standard you can't test it at all, since there is only one subcontractor location for all subcontractors. And you don't have an operation type there to deliver to another subcontractor. That's why I'm relying on your module.
But we could schedule a call to check this out anyway

**Comment by elvise** [comment]
@david-fleischmann Sure we can schedule a call, but it would be great if you could replicate a simple configuration in the odoo runbot just so we know the bug is on this module. (I have some doubts, because this module creates locations and types of operations for subcontractors nothing more)

**Comment by elvise** [comment]
@david-fleischmann 

As I suspected!
I tested in odoo V14 CE runbot with the same setup:

Products
- Finished > Subcontractor: SUB1
  - Semifinished > Subcontractor: SUB2
    - Element > Vendor: Vendor

I created a PO for the "Finished" product, a PO for the "Semifinished" product was automatically created and in Replenish I launched a PO for the "Element" product.

When I receive "Element" the QTY was updated while when I receive "Semifinished" the QTY was not updated.

**Comment by elvise** [comment]
@david-fleischmann same test in V15 (odoo runbot) and QTY is updated

**Comment by elvise** [comment]
hi @david-fleischmann i think this is the standard behaviour, in V15 there is a dedicate [module](https://github.com/odoo/odoo/tree/15.0/addons/mrp_subcontracting_dropshipping) maybe need to backport it

**Comment by david-fleischmann** [comment]
@elvise so how would you suggest to proceed here?
I think something has to be added to that sbc partner management module to make it work properly

**Comment by elvise** [comment]
> @elvise so how would you suggest to proceed here?
> 
> I think something has to be added to that sbc partner management module to make it work properly

@david-fleischmann Good morning!
From my side we need to back port this [module](https://github.com/odoo/odoo/tree/15.0/addons/mrp_subcontracting_dropshipping) from V15 to V14

**Comment by david-fleischmann** [comment]
@elvise this module is already in v15 and v14. I installed it at my customers location but it's still not working...

**Comment by francesco-ooops** [comment]
Hi @david-fleischmann , would you like to take a look at #1082 ? I think that's what we need for the flow you describe

**Comment by david-fleischmann** [comment]
> Hi @david-fleischmann , would you like to take a look at #1082 ? I think that's what we need for the flow you describe

@francesco-ooops as already stated in linked thread: thanks for your reply and digging into it! Will check it soon, didn't receive anymore notifications by github (spam folder...).
It really looks like this is the missing piece!
