### ISSUE TITLE
Real costs in manufacturing orders

### ISSUE THREAD

**Issue by vafonso** [OCA/manufacture#119]
Hi,
I am testing the Real Costs module for V8 and I figure out that the "Total Real Cost" on Manufacture order (field: real_cost Object: mrp.production) is different from the "Cost price" on Product form (field: standard_price Object: product.template)
In my testings, I set up average cost and also real cost for the manufactured item but none of options insert the correct cost in the item cost (as calculated in the real_cost field). For both test, the initial inventory was zero.
Also the stock journal entries are taking the cost price value, so these entries have incorrect values.

I tried to run the Runbot to make an example, but it look like to be off

Thanks for your help

Vinicius
![virtualbox_ubuntu_22_04_2016_10_04_49](https://cloud.githubusercontent.com/assets/15039028/14742280/af4429ea-0871-11e6-9357-a1c56fe869d3.png)
![virtualbox_ubuntu_22_04_2016_10_05_32](https://cloud.githubusercontent.com/assets/15039028/14742288/c3dd6b3c-0871-11e6-8bb3-4a023574c01d.png)

**Comment by vafonso** [comment]
As I am not expert into Odoo python, I looked that the _prepare_account_move_line takes the quant value for the stock journal move before the mrp calculates the new average/real cost price.
That means, the MO cost is correct calculated, but Odoo takes the quants moves costs
Let me know if this is really a problem.

Thanks in advance

Vinicius

**Comment by Sebmen** [comment]
Hi everyone
I have a similar problem on my Odoo V8 and the standard price is not updated after making a manufacturing order.

The Estimated real cost is correctly calculated in the "Extra information" tab on Manufacturing order but not reflected on the standard price of the product nor in the accounting entries (the actual standard price is used) when production is over.

**_Here are the manufactured product settings:_**
![mrp_prod](https://cloud.githubusercontent.com/assets/19420175/15345303/c43e5916-1ce8-11e6-96ac-793f6b405eee.png)

![mrp_prod_acc](https://cloud.githubusercontent.com/assets/19420175/15345388/6a5a0746-1ce9-11e6-8bbe-fd6e93a2cec9.png)

![mrp_prod_cat](https://cloud.githubusercontent.com/assets/19420175/15345391/704ee3c4-1ce9-11e6-82e7-6b33c7ce7899.png)

I hope someone could help us on this subject.

Thank you for your help in advance.
Best regards,
Seb.

**Comment by levkar** [comment]
It does not update standard price. It uses analytic to calculate real cost and updates inventory value of the finished good with this calculated value.

Note that "produce and consume" option will produce the finished good before consuming thus you will have wrong cost (if you use this options before consuming all products). It works if all products are consumed before produce operation because it needs to have real costs of consumed products.

**Comment by LoisRForgeFlow** [comment]
No answer, I consider the issue solved. Please feel free to reopen.
