### ISSUE TITLE
[quality_control_stock][8.0] No inspection created when transfer product using package

### ISSUE THREAD

**Issue by andhit-r** [OCA/manufacture#133]
module: quality_control_stock
version: 8.0

**Steps to reproduce**
1. Create a test
   ![selection_1](https://cloud.githubusercontent.com/assets/1947376/15702694/a9476d40-280b-11e6-80fb-57d1d7666d2d.png)
2. Assign QC trigger on product
   ![selection_2](https://cloud.githubusercontent.com/assets/1947376/15702738/e006d672-280b-11e6-829d-d15a9597b9c1.png)
3. Create a picking that will trigger QC
   ![selection_3](https://cloud.githubusercontent.com/assets/1947376/15702794/34b53b8c-280c-11e6-8ab2-474076b82017.png)
   ![selection_5](https://cloud.githubusercontent.com/assets/1947376/15702799/3c048230-280c-11e6-801f-4898aab9de43.png)
4. Transfered using package
   ![selection_4](https://cloud.githubusercontent.com/assets/1947376/15702820/4b0b7234-280c-11e6-9455-328cc869ecca.png)

**Current behavior**
Inspection did not created

**Expected behavior**
Inspection created

Is it by design? QC inspection won't trigger when transfer product using package

**Comment by pedrobaeza** [comment]
It's a non covered use case.

**Comment by andhit-r** [comment]
@pedrobaeza do you think it will useful for community if i add functionality to cover such use case? If you think it's useful should i add functionality on quality_control_stock or create new module?

Many thanks

**Comment by pedrobaeza** [comment]
Yes, it can be useful in the same module, as packages are also from stock module.

**Comment by andhit-r** [comment]
@pedrobaeza thanks for the confirmation. I will create PR for that functionality.
