### ISSUE TITLE
Bom Dismantling

### ISSUE THREAD

**Issue by mrparadies** [OCA/manufacture#135]
I am trying to use the mrp_bom_dismantling module with V9 enterprise.  I can successfully install the module and create a dismantling bom.  However, when I try to print the BOM Structure report of the dismantled bom I get the following error:
![image](https://cloud.githubusercontent.com/assets/17574418/15901637/b3dd068a-2d69-11e6-85a5-32a62448f34e.png)
When I try to print the BOM Structure report of the parent BOM, I get a similar error:
![image](https://cloud.githubusercontent.com/assets/17574418/15901686/e81713c8-2d69-11e6-9336-e125893e851a.png)
This prints fine when the dismantled BOM is not present.  Any idea whats going on?

**Comment by LoisRForgeFlow** [comment]
Closing due to aging, please feel free to reopen if you still experience the issue.
