### ISSUE TITLE
[16.0][BUG] mrp_multi_level: phantom/kit planning is broken

### ISSUE THREAD

**Issue by matt454357** [OCA/manufacture#1362]
Version 16.0 module `mrp_multi_level` is calculating incorrect demand quantity for component lines of kit/phantom BOMs.

Versions 14.0, 15.0, 17.0 are probably also affected.  I have not tested them.

## To Reproduce

Using demo data:

1. Set product PP-3 available quantity = 2.0
2. Create outbound move for product FP-3
3. Run MRP Multi Level

**Expected behavior**

Product FP-3 requires 4.0 units of PP-3.  We only have 2.0 units of PP-3 available.  We expect a planned order for 2.0 additional units of product PP-3, but the planned order is not generated.

**Additional context**

The core `mrp` module computes `qty_available`=2.0 for product SF-3, which is a kit.
The `mrp.multi.level` wizard double counts the available quantity of product PP-3.
The 2.0 available units of PP-3 are counted once as part of SF-3, and then counted again to satisfy the direct demand in FP-3.

![Screenshot at 2024-10-14 17-44-53](https://github.com/user-attachments/assets/5e74523d-d9d6-47cd-8180-7da710054eb5)

![Screenshot at 2024-10-14 17-46-21](https://github.com/user-attachments/assets/13a56441-9548-4cae-85fe-8d5beeeff28f)

**Comment by LoisRForgeFlow** [comment]
Fixed via https://github.com/OCA/manufacture/pull/1367
