### ISSUE TITLE
[16.0][BUG] mrp_multi_level: using wrong variant BOM

### ISSUE THREAD

**Issue by matt454357** [OCA/manufacture#1366]
Version 16.0 module mrp_multi_level is using the wrong variant BOM, when multiple variant BOMs exist.

This code should look for a variant specific BOM:

https://github.com/OCA/manufacture/blob/1f34d36b10fb9079add5e43cf7aaaf6811e2f60c/mrp_multi_level/wizards/mrp_multi_level.py#L183-L185

## To Reproduce

**Add attribute "Legs" and values "Steel" and "Aluminum" on product FP-2:**

![Screenshot at 2024-10-16 18-37-06](https://github.com/user-attachments/assets/fb2a7cdf-b8bb-4bc9-bfb9-106179f8c94a)

**Create BOMs for the two variants as follows:**

![Screenshot at 2024-10-16 18-32-09](https://github.com/user-attachments/assets/e95ff8f5-02ab-468a-8746-fcb8c1a93077)

![Screenshot at 2024-10-16 18-32-38](https://github.com/user-attachments/assets/c55b75e1-9c69-4313-94e8-8011e988424c)

**Create outbound move for product FP-2 (Aluminum):**

![Screenshot at 2024-10-16 18-42-28](https://github.com/user-attachments/assets/6bd7eb73-cbd1-4327-8e36-5c5018608740)

**We expect a planned order for SF-2, but we get a planned order for SF-1:**

![Screenshot at 2024-10-16 18-35-28](https://github.com/user-attachments/assets/525f226b-ceaa-41db-81f1-e1bd030bf9ef)

**Comment by matt454357** [comment]
The OCA module `product_configurator_mrp` has been creating individual BOMs for each variant since version 13.0.

https://github.com/OCA/product-configurator/tree/14.0/product_configurator_mrp

So, while the current method of selecting a BOM works with the core odoo demo data, it does not work with the OCA product configurator.

**Comment by LoisRForgeFlow** [comment]
Solved via https://github.com/OCA/manufacture/pull/1369
