### ISSUE TITLE
Dismantling a product which produce multiple sub-product of a same type with serial number

### ISSUE THREAD

**Issue by payam124** [OCA/manufacture#143]
my original post is here
https://www.odoo.com/forum/help-1/question/disassemble-a-server-106719
so this is the scenario

the product is a server
it is made of different parts and each part has a serial number
i.e.
src-CTO-0001
  SN: SRV0001 (is created during manufacturing process)
1xChassis, SN:
   CH00001
2xCPU, SN:
  CPU0001
  CPU0002
2x Memory, SN:
   MEM0001
   MEM0002

I create the BOM, I manufactured a server, allocated serial numbers and ...
then I used the BOM and crated a dismantling BoM
then created a Dismantling order. confirmed it. 
in the produce section, I entered the serail number of the server to be consumed.
then in the list of "Products to produce lots", for items which I had multiple of them in the BoM, there was only one row and I was able to enter just a single serial
first of all, my expectation was those serials got filled based on the used products in the manufacturing process
furthermore, the system did not allow me to enter multiple serials for items which more than one of them were supposed to get produced

also I got this error:
"You should only receive by the piece with the same serial number"

**Comment by LoisRForgeFlow** [comment]
Closing due to aging, please feel free to reopen.
