### ISSUE TITLE
[8.0] mrp_operations_extension: mrp.operation.workcenter fields time_start and time_stop are ignored.

### ISSUE THREAD

**Issue by rubencabrera** [OCA/manufacture#166]
The model mrp.operation.workcenter adds op_wc_lines where we can override values from the workcenter, but the values for time_start and time_stop are not taken into account for the mrp.routing.workcenter lines.

This information could be important for cost estimation and users expect it to be, at least, added to the value of hour_nbr.

**Comment by anajuaristi** [comment]
@agaldona could you please take a look to see this happens?.

If time_start and time_end are included on mrp.routing.workcenter lines, it should go to the OT.

**Comment by agaldona** [comment]
There are time_start and time_stop fields in workcenters and in workorders. When creating the MO costs this fields are taken into account but only if you have specified the pre_op_product and the post_op_product in the workcenter. Maybe this is the problem.
