### ISSUE TITLE
[9.0] mrp_bom_dismantling: Dependency not used?

### ISSUE THREAD

**Issue by LoisRForgeFlow** [OCA/manufacture#189]
I'm wondering why this dependency is needed here: https://github.com/OCA/manufacture/blob/9.0/mrp_bom_dismantling/__openerp__.py#L16

cc @cyrilgdn

**Comment by cyrilgdn** [comment]
@lreficent He uses components computation method from this module.

This method https://github.com/OCA/stock-logistics-warehouse/blob/9.0/stock_available_mrp/models/product_product.py#L92
Is called here: https://github.com/OCA/manufacture/blob/9.0/mrp_bom_dismantling/models/mrp_bom.py#L153

**Comment by JordiBForgeFlow** [comment]
@cyrilgdn I propose to remove the dependency, and define a new method that does the same in this module. Because that method is generic. We are really not instested in what 'stock_available_mrp' does, and it is adding unneded complexity to us. Better decouple, IMHO. Can we propose a PR?

**Comment by LoisRForgeFlow** [comment]
Related PR has been merged.
