### ISSUE TITLE
MTO-MTS rule: the minimal quantity is  not taken into account

### ISSUE THREAD

**Issue by ccandito** [OCA/manufacture#230]
Dear All,
I've implemented both "MRP MTO with Stock" and "Stock MTS+MTO Rule" Apps.
I've entered a SO for Finished product and the net calculation (requirement - stock) has been performed successfully creating a MO with proper quantitu
The same happened for raw materials for BOM explotion and a PO has been created with the proper quantity. Unfortunately the PO's quantity has not taken into account the minimal quantity set in vendor price list in product master data.
Regards
claudio candito

**Comment by LoisRForgeFlow** [comment]
Hi @ccandito 

Looking at the code seems that you are right. Feel free to propose a PR to fix it.
