### ISSUE TITLE
[10] no trigger in quality control

### ISSUE THREAD

**Issue by mauroanelli2017** [OCA/manufacture#243]
Dears,
i install quality control module on Odoo 10 CE but when i go to set the trigger in product form, trigger field is empty and cannot select anything.

**Comment by pedrobaeza** [comment]
Install quality_control_mrp or quality_control_stock.

**Comment by mauroanelli2017** [comment]
cannot find for odoo 10 ce

**Comment by pedrobaeza** [comment]
Not migrated yet

**Comment by mauroanelli2017** [comment]
do you have a timeline for migrating these? because without them quality controll works half.
thanks

**Comment by pedrobaeza** [comment]
Me not. If you want this to get migrated, contribute either making you the migration or funding a developer to do it.
