### ISSUE TITLE
[11.0] mrp_bom_equivalent

### ISSUE THREAD

**Issue by max3903** [OCA/manufacture#248]
This module considers all the the products in the same product category to be equivalent and interchangeable in a Manufacturing Order, using the product priority. The user can specify non-equivalent products to a part on a BOM.

# Usage
- Go to Manufacturing > Master Data > Bill of Materials
- Create or update a BOM to check the box "Use Equivalences"
- Set the non-equivalent products among the products of the same category

# Dependencies
- https://github.com/OCA/product-attribute/issues/322

**Comment by bodedra** [comment]
@max3903 

PR #250 is ready for review.
