### ISSUE TITLE
[11.0] mrp_barcode

### ISSUE THREAD

**Issue by max3903** [OCA/manufacture#268]
# Barcode Scanning in Manufacturing

This module allows you to use a barcode scanner to avoid clicking in the tablet interface of the MRP module. 

Limitation: This module assumes that there is only one lot/SN of a component in a bin (Scanning a bin allows us to find the lot/SN number).

# Configuration

Print the following PDF document to have the barcode of the manufacturing operations:

* Print (the label of the serial number of the produced item)
* Validate
* Mark as done
* Pass (quality check)
* Fail (quality check)

# Usage

* Go to Manufacturing
* Click on the "Work Orders" button of your work center
* Open the first one
* The SN of the produced item will be automatically created and set
* You can click on Print to print the label of the SN of the produced item
* If a component is tracked by lot or serial number and there is only one number, the number is selected automatically otherwise you scan the barcode of the location
* The location of the selected lot/SN of the component is displayed

# Dependency

* quality_mrp

# License

LGPL

**Comment by max3903** [comment]
# Version 1.0.1

- [ ] Change the default filter in the work orders to remove the "In Progress" and only show the work orders to do.
- [ ] If the produced item is tracked by serial number, set the next serial number automatically when the work order is recorded
- [ ] Avoid scanning barcode of the component if there is only one number in the dropdown list. Show the stock location to pick it.

**Comment by LoisRForgeFlow** [comment]
Hi @max3903 

Just a quick comment: you shouldn't depend on 'quality_mrp'  as it is a enterprise module, should you?

**Comment by max3903** [comment]
Hi @lreficent,

Yes I should. The module is customizing a view from `quality_mrp`: 
https://github.com/OCA/manufacture/pull/269/files#diff-adfd3d5275cc973ee573d9a590083ffdR8

**Comment by LoisRForgeFlow** [comment]
@max3903 What I meant was: OCA modules should be always designed to work on top of Odoo CE. 

I don't know if there is a strict policy regarding this but I've never seen dependencies with EE modules at OCA. Plus, runbot will always fail to build your module as it doesn't use EE code.

**Comment by pedrobaeza** [comment]
Yes, OCA modules can't depend on a proprietary module.

**Comment by max3903** [comment]
Yes they can:

![datas](https://user-images.githubusercontent.com/939952/40488425-60981e46-5f2c-11e8-9093-f74798527ea8.jpeg)

Can't we skip the installation of this module in the test execution and runbot?

**Comment by pedrobaeza** [comment]
> Can't we skip the installation of this module in the test execution and runbot?

Not easily, and I personally prefer to not have such modules here.
