### ISSUE TITLE
[11.0] mrp_mto_with_stock consumed materials are doubled.

### ISSUE THREAD

**Issue by oerp-odoo** [OCA/manufacture#279]
I don't know If I understand configuration of this module or intention, but it looks like it messes up manufacturing order consumed materials when used.

I'm using default mode (where nothing is enabled on warehouse to have forecast quantity mode). My product that is consumed in MO has `wh/stock` location set as `MTO/MTS` location. And uses `Buy` route only.

It seems it works correctly till materials are needed to be consumed (taking quantity from stock, ordering missing quantity, reserving needed quantity). When I start producing MO, then consumed materials stock moves duplicate.

For example If I manufacture a product where I need 5 units of material A and I have 2 units in stock and 3 are ordered. Then when I receive remaining materials, after pressing produce button, I see such stock moves (instead of 2 moves for 2 units and 3 ordered units):

```
06/15/2018 14:48:57	MO/00015	T3	WH/Stock	Virtual Locations/Production	3.000	Done

06/15/2018 14:48:57	MO/00015	T4 MF	Virtual Locations/Production	WH/Stock	5.000	Done

06/15/2018 14:48:57	MO/00015	T3	WH/Stock	Virtual Locations/Production	2.000	Done

06/15/2018 14:48:57	MO/00015	T3	WH/Stock	Virtual Locations/Production	3.000	Done

06/15/2018 14:48:57	MO/00015	T3	WH/Stock	Virtual Locations/Production	2.000	Done
```
Which means you use more materials than were required for an MO.

P.S. You can see my attached video how I reproduced this behavior.

[mrp-mto-with-stock-bug.ogv.zip](https://github.com/OCA/manufacture/files/2105959/mrp-mto-with-stock-bug.ogv.zip)

**Comment by oerp-odoo** [comment]
I have created a fix for this issue: https://github.com/OCA/manufacture/pull/280

**Comment by LoisRForgeFlow** [comment]
This can be closed too I think as it is solved.

Thanks!

**Comment by oerp-odoo** [comment]
Yes. Forgot to close it:)
