### ISSUE TITLE
[10.0] [mrp_mto_with_stock]  Not working at all

### ISSUE THREAD

**Issue by PetriHeik** [OCA/manufacture#295]
Hello,

I am having troubles with this module. It is not working at all. If I have 5 units of product A in stock and I sell 6 units. The module should check stock and create MO for one more, right?

I have set the manufacturing MTS/MTO location for my product but if I leave the MTO box checked, odoo will create MO for 6 units. And If I leave it unchecked, odoo will not create any MO.

Thanks.

**Comment by LoisRForgeFlow** [comment]
Hi @PetriHeik 

To work properly the 'Make to Order' box must be unchecked.

**Comment by PetriHeik** [comment]
Hello,

If I leave Make to Order box unchecked, Odoo will not create any MO.

**Comment by LoisRForgeFlow** [comment]
Hi @PetriHeik 

* have you got enough inventory for the components? if yes, no need for auto-created MOs.
* have you set the MTO/MTS locations for the components? if not, no automatic MO will be created.

Check this two points please.

**Comment by PetriHeik** [comment]
Hello and thank you for the reply,

I have checked both of those points and it is not working. Here is a couple of pictures of the settings. Our system is in Finnish, but I think you can locate right places.

For example product N220
![kuva](https://user-images.githubusercontent.com/42260926/45204045-be211100-b286-11e8-9c39-4a4f8aae3f27.png)

I sell 5 items from KIUR
![kuva](https://user-images.githubusercontent.com/42260926/45204058-c5e0b580-b286-11e8-9899-b802c8682b45.png)

So when I confirm the sale, Odoo should create MO for three N220, right? auto-created MO:s are not created.

Any luck of re-installing the module?

Thanks,
Petri

**Comment by LoisRForgeFlow** [comment]
With that I cannot tell what is wrong, could you please try to reproduce your error in runbot: https://runbot.odoo-community.org/runbot/repo/github-com-oca-manufacture-129 (select any instance of v 10.0).

Thanks
