### ISSUE TITLE
equivalent products

### ISSUE THREAD

**Issue by ccandito** [OCA/manufacture#299]
Dear All,
I've installed the "mrp_bom_equivalent" module and afterwards the "ddmrp_production_equivalent" also.
In both test cases, the equivalent product has not been determined.
What I did is:
in the BOM I've checked the "use equivalence" indicator for a component material;
this component material has not stock on hand;
another material with the same category has enough stock.
Unfortunately the second component is not determined in BOM explosion when a MO has been created.
Regards
Claudio

**Comment by max3903** [comment]
Hello @ccandito,

Is the equivalent product in a subcategory of the main product on the BOM line?
What is the buffer status of the main product?

**Comment by ccandito** [comment]
Hi Maxime,
thanks for your prompt reply.
1) are you speaking about the field categ_id? if so, yes: the equivalent
product and the bom component belong to the same category
2) sorry, I did not grab what you mean
Regards
claudio

Il giorno dom 26 ago 2018 alle ore 03:15 Maxime Chambreuil <
notifications@github.com> ha scritto:

**Comment by max3903** [comment]
When the MO is created, Odoo checks the DDMRP buffer status (netflow
position is green yellow or red) of the main product. If it's not green, it
looks at the DDMRP buffer status of the equivalent products. If none is
green, the main product is not replaced.

**Comment by ccandito** [comment]
Dear Maxime,
I've created two reorder point profiles for component and its equivalent
product with a replenishment/purchase buffer profile and ..... the
substitution works in MO parts list (thanks for your support).
Regards
Claudio

Il giorno dom 26 ago 2018 alle ore 12:24 Maxime Chambreuil <
notifications@github.com> ha scritto:

**Comment by ccandito** [comment]
Dear Maxime,
just a remark you probably already know:
for activating this feature I had to create ordering points for bom components; that means these components are not taken into account in requirement dependent determination (PUSH logic) because an ordering point (PULL logic, so DDMRP) has been activate for them.
Unfortunately this is a big constraint to use this feature in a manufacturing environment.
thanks a lot for your support
Regards
claudio
