### ISSUE TITLE
MRP multi level : misleading figures in MRP Inventory view - version 11

### ISSUE THREAD

**Issue by ccandito** [OCA/manufacture#313]
Dear All,
I've set up the mail stock location as MRP Area.
I'm using PO with 2 steps, i.e. "input location" and afterwards "stock location".
After performing the initial receipt into "input location" the stock quantity is displayed in "MRP inventory" as "Starting Inventory" and not as "supply".
Regards
claudio

**Comment by LoisRForgeFlow** [comment]
what is the "mail stock location"?

**Comment by ccandito** [comment]
sorry
main stock location
it is linked directly to its warehouse so you could find it into the
warehouse table
regards
claudio

Il giorno mar 16 ott 2018 alle ore 12:33 Lois Rilo <notifications@github.com>
ha scritto:
