### ISSUE TITLE
mrp_multi_level : cannot update mrp products

### ISSUE THREAD

**Issue by didier1969** [OCA/manufacture#314]
First, thanks for this excellent module !

I am currently testing your module, in order to implement soon. I am able to generate the mrp.inventory entries from the MRP Multi Level job, but I am getting fancy daily values.

I suppose there is a way to group and round-up the quantities to procure through the MRP Products additional fields.

But in view Manufacturing>MRP>MRP Products, the fields are read only. And I did not find a way to update them, nor understand their relation with already existing information, like the scheduling rules, supplier's info data, etc.

Thanks for your help / explanation
Didier

![image](https://user-images.githubusercontent.com/2456309/46920808-80cd4300-cfeb-11e8-8ffd-61a77cc79e53.png)

**Comment by JordiBForgeFlow** [comment]
Hi! Please review https://github.com/OCA/manufacture/pull/297

**Comment by sswapnesh** [comment]
Is it already fixed in #297 ? I think so (Maybe)

**Comment by bealdav** [comment]
Ok @didier1969 then can be closed now.
