### ISSUE TITLE
quality_control does not separate quality inspections for products with a serial number

### ISSUE THREAD

**Issue by Eracydani** [OCA/manufacture#332]
Hi,

I was looking for help for the quality_control module (v11) and Odoo's webpage suggested this forum. 

My colleagues, who are already using quality_control on Odoo v8, showed me that, when they purchase products with serial number traceability, the quality controls set for them appear separated in Odoo's Quality Control tab e.g. they buy 30 products and 30 quality checks appear when they transfer them to stock. When the traceability is set to lots and not serial numbers, the quality controls appear for the whole lot e.g. they buy 30 products and just 1 quality check appears when they transfer them. 

However, when I test it in v11, the quality control works the same for products with either lot or serial number traceability: only 1 quality check appears. The difference is that, since purchases of products with serial number traceability include several serial numbers, the quality inspections only refer to the first serial number found in the purchase (though including the real quantity of products bought), whereas for products with lot traceability, the quality inspection refers to the actual lot number.

Is this a problem of the version, or a deliberate decision by the OCA team for the new version? Or is there any kind of configuration option that I can select to make quality inspections appear as they do to my colleagues with Odoo v8?

Thank you.

**Comment by pedrobaeza** [comment]
I think it's a not implemented feature.

**Comment by Eracydani** [comment]
Thanks for the reply, Pedro! You mean the separate quality inspections feature is something the guys using v8 must have programmed for themselves, or that you decided to take that feature out for Odoo v11?

**Comment by pedrobaeza** [comment]
AFAIK, I don't remember that we implement that feature, so:

- It was an accident that in v8 that works that way.
- Or it was implemented outside the module.

**Comment by Eracydani** [comment]
Okay thanks!
