### ISSUE TITLE
mrp_mto_with_stock  material qty in PO double than it in MO.

### ISSUE THREAD

**Issue by xerxesnoPT** [OCA/manufacture#334]
Dear All,
i install the mrp_mto_with_stock in odoo11. and  use the first mode(default mode). i found in the procurement create associate purchase order .the qty of material is not correct
for exp:
-  i create a product named "Car"。i set the bom of car is "Engine" X1.
- see the picture:
![2019-01-24 4 45 16](https://user-images.githubusercontent.com/26807644/51665741-73b2ed80-1ff7-11e9-8e0b-6cac1eafd51b.png)
- the product engine set is:
![2019-01-24 4 46 47](https://user-images.githubusercontent.com/26807644/51665873-abba3080-1ff7-11e9-9a30-7fbaa564d532.png)
- i update the on hand qty  of "Engine" to 5.
- the problem now is that when i manufactur 6 Cars. in the MO, the move qty is split to 5 (use stock on hand), 1(use mto procurement). but when the procurement run, in the associate purchase.the qty of the "Engine" is 2. 
![2019-01-24 5 05 17](https://user-images.githubusercontent.com/26807644/51667124-4287ec80-1ffa-11e9-90ee-6323af213b54.png)
![2019-01-24 5 05 45](https://user-images.githubusercontent.com/26807644/51667144-54698f80-1ffa-11e9-954a-c42c1faf3b01.png)

**Comment by egonravalah** [comment]
We made a fix for that, will upload shortly

**Comment by xerxesnoPT** [comment]
thank you very much @egonravalah

**Comment by xerxesnoPT** [comment]
@egonravalah  dear friend, can you help me to fix this issue?

**Comment by desdelinux** [comment]
> We made a fix for that, will upload shortly

@egonravalah Hello, can you upload your solution to this case?
