### ISSUE TITLE
[12:0]MRP Group MO by Product: Possible Issue

### ISSUE THREAD

**Issue by sbinmahfooz** [OCA/manufacture#396]
Hi,
i wanted to raise a possbile issue in the MRP group by Product App, following is the scenario
I have a BOM of components that are all manufactured with different routs, as follows:
**Product Name:** Sandwich X - Manufcture bom
**Detailed Bom**: 
1- Filling A - Manufactured bom  
2- Filling B - Manufactured bom  
3- Sandwich Bases - Manufactured bom  

Now, when i create a sales order: the first run the MO is created and grouping the components properly, 
![image](https://user-images.githubusercontent.com/52846567/63482715-941a2c00-c4a2-11e9-8110-84feb0cf2e22.png)

however, when i have second sales order, the top product Sandwich X is added, while the components are not.
![image](https://user-images.githubusercontent.com/52846567/63482762-c3c93400-c4a2-11e9-8098-9f2baa8be097.png)
is this expected behavior or something is not right?

**Comment by pedrobaeza** [comment]
Do you mean the raw materials are not recomputed for the new quantity 4.000?

**Comment by pedrobaeza** [comment]
@skukered you were the one migrating the module. Can you check?

**Comment by sbinmahfooz** [comment]
Yes,
The new quantity of the components is not recomputed it shud go from 2 to 4
Regards



---- On Thu, 22 Aug 2019 10:53:31 +0300 notifications@github.com wrote ----



Do you mean the raw materials are not recomputed for the new quantity 4.000?

**Comment by sbinmahfooz** [comment]
@skukered any help pls

**Comment by skukered** [comment]
I could check it out on the weekend.

**Comment by sbinmahfooz** [comment]
thanks appreciate it

**Comment by skukered** [comment]
I have my doubts if it is an issue of this module or of the mrp module. I think the 'change_prod_qty' method of 'change.production.qty' should make these changes...

**Comment by sbinmahfooz** [comment]
I go with ur doubts, for the following reason,
When I use different scenario of defining routings at MRP, what happens is that, it does not group the top product Sandwich X, while it groups the components.
Having this, what could be possible solution

**Comment by sbinmahfooz** [comment]
Hi, i  have recieved the following bug
![image](https://user-images.githubusercontent.com/52846567/64075463-682c5100-ccc1-11e9-840d-1fd9d3194c9e.png)

**Comment by pedrobaeza** [comment]
@skukered any news?
