### ISSUE TITLE
mrp_production_grouped_by_product: Nothing happens

### ISSUE THREAD

**Issue by jcarvalhido** [OCA/manufacture#405]
Hi,
I installed the mrp_production_grouped_by_product module on Community V12, but nothing happens. Whenever I create an SO from the same product, it generates additional MOs, one MO for each SO.

**Comment by pedrobaeza** [comment]
Have you checked https://github.com/OCA/manufacture/tree/12.0/mrp_production_grouped_by_product#configuration ?

**Comment by jcarvalhido** [comment]
I think so
![printscreen](https://user-images.githubusercontent.com/37071642/65508440-1a71c580-dec8-11e9-9662-962890f1e6e2.png)
![printscreen2](https://user-images.githubusercontent.com/37071642/65508441-1a71c580-dec8-11e9-91c2-ee135332d7c4.png)

**Comment by pedrobaeza** [comment]
@skukered can you check this one as well?
