### ISSUE TITLE
[12.0] Question: quality_control and quality_control Enterprise

### ISSUE THREAD

**Issue by igallart** [OCA/manufacture#417]
Hello, I have seen that in the enterprise version there is a module called quality_control, just like that of the OCA. Is there any incompatibility?

**Comment by bodedra** [comment]
@igallart IMO, both modules have their unique functionality. Additionally, there is no duplicate fields introduce at object level. But it can not survive together.

**Comment by pedrobaeza** [comment]
The only problem is the module name, that collapses and it's not shown in Odoo apps.

**Comment by igallart** [comment]
So, the only problem is that either Enterprise or OCA version, but not both, ok?

**Comment by pedrobaeza** [comment]
Yeah, that's true as well.

**Comment by igallart** [comment]
Thank you, and perhaps the idea of changing the name to have both in the future could be valued. Sorry for my bad english.
