### ISSUE TITLE
[12.0] Manufacturing request make2order 

### ISSUE THREAD

**Issue by CasVissers-360ERP** [OCA/manufacture#423]
```
    def _quantity_in_progress(self):
        res = super()._quantity_in_progress()
        mrp_requests = self.env['mrp.production.request'].search([
            ('state', 'not in', ('done', 'cancel')),
            ('orderpoint_id', 'in', self.ids),
        ])
        for rec in mrp_requests:
            res[rec.orderpoint_id.id] += rec.product_uom_id._compute_quantity(
                rec.pending_qty, rec.orderpoint_id.product_uom, round=False)
        return res
```
This method ensures reordering rules are not triggered when manufacturing requests are found. 

Issue: 
If the manufacturing request is created by a make2order sale order line, orderpoint_id is different and the reordering rule create unwanted extra manufacturing requests.

**Comment by pedrobaeza** [comment]
Can you please include some steps to reproduce the problem?

**Comment by LoisRForgeFlow** [comment]
@CasVissers it can be that this happen, as we have never used MR's in a MTO strat. Please open a PR addressing it that includes a test case and I would review it.

**Comment by CasVissers-360ERP** [comment]
@lreficent Yes I found out later that MR's are not able to handle MTO. Especially when dealing with multi-level bom and "stock -> production" stock moves. I fixed both with automated actions for now. Will try to make a PR asap. Will definitely need some help since I'm officially still a consultant.

**Comment by LoisRForgeFlow** [comment]
@CasVissers Great, I will be happy to help you.
