### ISSUE TITLE
Port to odoo 12

### ISSUE THREAD

**Issue by batona** [OCA/manufacture#438]
Hello! Are you planning to porting this module to odoo v12?
If not, what cost may be for porting it? 
Thanks.

module: mrp_sale_info
version: 11.0

**Steps to reproduce**
- ...

**Current behavior**

**Expected behavior**

**Comment by bodedra** [comment]
@batona mrp_sale_info module is under migrating process, so you may help to review it at https://github.com/OCA/manufacture/pull/350

**Comment by batona** [comment]
Thanks I'll try it

пн, 9 дек. 2019 г., 7:41 Bhavesh Odedra <notifications@github.com>:
