### ISSUE TITLE
Any documentation?

### ISSUE THREAD

**Issue by deantheiceman** [OCA/manufacture#497]
Hi,

I stumbled across this as I was looking at Odoo for our MRP. Is this independent from the MRP and quality modules provided by Odoo Enterprise?

Is there any documentation about how to use this, if not how do I go about installing this? 
Will this work with my Odoo 13 installation? 

Thank you

**Comment by pedrobaeza** [comment]
Yes, these are other modules. See each README for a description of their features.

**Comment by deantheiceman** [comment]
I copied this repository into my custom addons folder but do not see it listed as an option to install. Is there any other steps I need to do?

Will it work with Odoo 13 community edition?

**Comment by pedrobaeza** [comment]
That are general deployment questions that you should do in forums, not here. The migrated modules for 13.0 are in the 13.0 branch.
