### ISSUE TITLE
[12.0] mrp_multi_level: Phantom BoM items handled like normal BoM items

### ISSUE THREAD

**Issue by matt454357** [OCA/manufacture#504]
**Impacted versions:** 12.0, 13.0

**Steps to reproduce:** (using demo data)
1. Change BoM for product SF-1 to phantom (BoM Type = Kit)
1. Create delivery order picking for FP-2
1. Run MRP Multi Level
1. Go to MRP Inventory list and look at product SF-1

**Current behavior:**
The user is prompted to procure product SF-1.  Doing so creates a manufacturing order for SF-1.  Attempting to Produce the MO results in an error message: "You cannot produce a MO with a bom kit product."

**Expected behavior:**
The user should not be able to manufacture products with BoM Type = Kit.

![image](https://user-images.githubusercontent.com/7604932/83435721-f45ad880-a3f9-11ea-87ee-b687da0f2a10.png)

**Comment by bealdav** [comment]
cc @JordiBForgeFlow @LoisRForgeFlow
