### ISSUE TITLE
[12.0] Mrp Subcontracting Phase of Work

### ISSUE THREAD

**Issue by Zephyria77** [OCA/manufacture#517]
Good Morning, I have been using odoo for 4 years in three different company. I have searched various discussions and module about subcontracting but nothing that met my idea. Now I'm using odoo V12 CE with workorder and routing. This is optimal for my workflow but some operation of routing must be subcontracted and I am forced to use multi level bom with many many intermediate steps while if I could use subcontracting on routing operation (phase of work), I can solve it with a unique bom. 
Please let me explain with an example:
We are a company that produce mechanical part on customer drawing. 
We Have turning and milling center.
Our products has various phases to obtain finished products, some internal, some external. 
Example one:
1 we buy raw material (bar of stainless Steel) 
2 turning (internal) 
3 milling (internal) 
4 Thermal treatment (subcontract 1) 
5 grinding (subcontract 2)
6 laser engrave (subcontract 3)
7 polishing (internal) 
This is a Typical workflow for a product that we manage with workorder. How you can see there is three different subcontractor involved. 
Example two:
1 we buy raw material (bar of stainless Steel)
2 special turning (subcontract 4) 
3 polishing (internal) 
4 electrolitic treatment (subcontract 5) 
5 chamfering (internal) 
The difference between two workflow is that in the first example we subcontract semifinished product so the unit of measure is unit. 
In the second one we send to subcontractor a bar of stainless Steel (unit of measure meter) 

Please share your opinion, thanks

**Comment by bealdav** [comment]
Hi @Zephyria77 I share your opinion about subcontracting in Odoo v13.

It's incomplete. You're example are self explaining
In industry there is 2 kind of sub contracting:

- subcontract a product (product defined by myself but executed by others partners) : in odoo you can set subcontractors on bom (header bom)
- subcontract an operation (subcontract for one particular routing step to other partners). It's not a product reference which define the purchase but an operation on a product (finally a service, not a product) => this case is not managed by Odoo

Seems there are no changes in v14 https://github.com/odoo/odoo/blob/master/addons/mrp_subcontracting/models/mrp_bom.py#L13

cc @LoisRForgeFlow @hparfr

**Comment by hparfr** [comment]
In v10, we have added the subcontracting for one of our client. I didn't follow precisely what Odoo SA did implement in v11+ but I doubt it support complex supply chain.

Some key requirements of our project:
- BOM up to 8 levels (each level a different subcontractor)
- longest path (= sum of lead time) about 6 month
- some suppliers are chosen after the beginning of the firsts MO (lower levels, close to raw materials)
- some parts of the BOM can change during the process (!)
- majority of MTS + MTO
- each supplier his warehouse (we manage stock at their place: picking in of raw materials, production, picking out of finished goods).
- ...

The principals modules are the following. Readme are not up to date, but the code is used in prod:
- mrp_subcontracted: each subcontracted MO creates a Purchase Order.
https://github.com/akretion/ak-odoo-incubator/tree/10-mrp_subcontracted

- mrp_subcontract_location : 
  - create and activate route between suppliers on each product
  - allows to change the subcontractor (wh) of a bom (cancel old moves in old wh, recreate moves in new wh, source only needed raw materials) 
https://github.com/akretion/ak-odoo-incubator/tree/10-mrp_subcontract_location_wip



About your example, I think it make sense to have products between each steps and have a bom for each level.
