### ISSUE TITLE
[12.0] Kit sub-bom remove component ignored when updating MO

### ISSUE THREAD

**Issue by sergiocorato** [OCA/manufacture#525]
When updating a manufacturing order with a sub-bom of type kit, the component are not removed if removed from the sub-bom.

Video:
![mo_subbom1](https://user-images.githubusercontent.com/7657311/93176917-44a04100-f732-11ea-8e9d-0bbc9d31d496.gif)

**Comment by pedrobaeza** [comment]
But is this from any module of this repository?

**Comment by sergiocorato** [comment]
No, should I put it in Odoo issues?

**Comment by pedrobaeza** [comment]
Yes, that's the idea. The GIF is very small though, and so I can't say if this is a real bug.

**Comment by sergiocorato** [comment]
moved to https://github.com/odoo/odoo/issues/57702
