### ISSUE TITLE
[13.0] Only one Manufacture Request being created by the  sale.

### ISSUE THREAD

**Issue by guimarc-br** [OCA/manufacture#529]
Hello Guys

On  a Project that I am   working we have the expectation to get  one MR for each  product from the sale/order that does not have the quantity and is Manufacture Request.

**model:** mrp_production_request
**file** : stock_rule.py

I made a debug here and check that is created in the  method  

```
def _run_manufacture(self, procurements):
        for procurement, _rule in procurements:
            if self._need_production_request(procurement.product_id):
                return self._run_production_request(
                    procurement.product_id,
                    procurement.product_qty,
                    procurement.product_uom,
                    procurement.location_id,
                    procurement.name,
                    procurement.origin,
                    procurement.values,
                    procurement.company_id,

```
I could see that is  happening due the **_return_** command,  so when find one product that is manufacture request return the method.

So to handle the expectation on  my project  I just removed the  **_return command_**  and now all products that needs a MR are created.

My question  is guys : This is how this should work ?  or its a bug?.  If it is how was designed I can  change on my project as I did , I am just confirming.

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

Little tip: you must activate MTO route in the product.

**Comment by LoisRForgeFlow** [comment]
@pedrobaeza I think this is actually a bug, I'm reopening the issue.

@guimarc-br Hi, thanks for reporting it. Would you mind opening a Pull Request fixing the issue? Thanks!

**Comment by guimarc-br** [comment]
Hi Folks

Pull Request created : https://github.com/OCA/manufacture/pull/532

Please take a look.

**Comment by LoisRForgeFlow** [comment]
Fixed (https://github.com/OCA/manufacture/pull/549).
