### ISSUE TITLE
Standard Price

### ISSUE THREAD

**Issue by JMODaERP** [OCA/manufacture#55]
When the  cost method is average price: the  standard  cost (manual)  should be update manually up, by  the user as a target cost or the cost trends over a significant period.

**Comment by rafaelbn** [comment]
@jbeficent @pedrobaeza @anajuaristi what do you think?

**Comment by elicoidal** [comment]
Hi,
Thanks for your inquiry.
Average cost calculation is not manually performed in Odoo. It is updated when the incoming shipment is validated, based on the PO price (without VAT).
The value of the goods from the incoming shipment are added to the current stock value and the average is calculated accordingly (total stock value / number in the UoM). Delivery orders will use the average price at the moment of the transaction.
If you need a target cost you might want to use the standard cost calculation method which actually allow to have a fix standard cost.
A third approach would be a FIFO "real cost" in which the delivery orders will use the recorded cost of inventory following FIFO rules.
Let us know if this answer your question.

**Comment by JordiBForgeFlow** [comment]
@JMODaERP Can you elaborate your statement? There must be some reason for you to raise the issue. It's not clear to me at all.

**Comment by JMODaERP** [comment]
I think that I did not rather well my inquiry, or at less the query should be oriented to other forum. 
But ,  in any way,    i go to express my idea:

The problem arises, because i need two price, one: the average price for the product for evaluated my warehouse and for calculate the inventory turnover and other price The best way, (you know; As is - To be)  :

a) Calculating the cost price when the method is Average Price

When the warehouse is valued by method of the Average Weighted Price (cost_method del          objeto product.product) , this algorithm should be applied:

Average Price (Pm) = (Si \* Pma) + (E \* PC) / (Sf + E).

Where:

Si = initial Stock (Before the movement of Entry).
Pma = average Price before the entry.
Sf = End Stock (After movement of Entry).
E: units of Entry (purchase or manufacture).
PC = Cost price of the Entry (It Will Be Purchase price or Cost price of Production.).

When: Si > 0 and Pma > 0.

standard-price (del objeto product.product)= Pm (calculated).

b) I need, a second price, the real stándard price. This stándard price will guide the purchase and  manufacture. This standard price can be a indicator or simply the tendency of another previous period.

I know Odoo only has one price depending del cost method, but i think that can be a very good improvement.

Thanks.

**Comment by anajuaristi** [comment]
Yes. In OdooMRP we have got the module mrp_stimated_cost that is adding that "manual_standar_cost" field on product.product form.

This value will be only updated 2 ways
1. User changes it
2. Someone is simulating MO cost using ficticious MO and wants to update the cost of the semi-finished or finished product. Ficticious MOs will ONLY update that field to not modify average values calculated by system.

So with this module you can set Odoo standar behavior "average cost method" on product form and you can use "manual_standar_cost" field to set the value you want knowing that system will not modify it in any automatic process. 
Wishing this helps:
Ana

**Comment by JMODaERP** [comment]
cc @rafaelbn

**Comment by pedrobaeza** [comment]
Current _mrp_production_real_cost_ module updates only the price of the stock move here: https://github.com/OCA/manufacture/blob/8.0/mrp_production_real_cost/models/mrp_production.py#L35, and the proposed PR for _mrp_production_estimated_cost_ only update standard price under demand here: https://github.com/OCA/manufacture/pull/64/files#diff-800ef06f83140fa164e11b737fbc5141R263, so there's nothing wrong with current approach.
