### ISSUE TITLE
RFC adjust Manuf Order qty according to workcenter capacity using mrp_manufacturing_request

### ISSUE THREAD

**Issue by bealdav** [OCA/manufacture#555]
Use Case: food industry

Considering production a mixture of products in machine, which we can be called a mixer.
You have several mixers with different capacities.
Capacity may vary from a product to another for the same machine : product A 180 kg, product B 75 kg .

According to a selection of machines (workcenters) and the product manufactured I want to define a global quantity in a manufacturing_request and then create 1 MO by machine for traceability purpose.

Does it useful as an OCA module ?

Have you any advice (or requirement) specifically to store the relation between product and capacity by machine ?

cc @LoisRForgeFlow @JordiBForgeFlow 

Thanks

**Comment by LoisRForgeFlow** [comment]
Hi @bealdav 

We don't currently have a use case for it but I think it is still interesting to have production request capabilities extended with such a feature, you can propose here at OCA as an extension module of mrp_prodcution_request, I will be glad to review it.

**Comment by bealdav** [comment]
Hi @LoisRForgeFlow 
before fine tune my module could you have a first look 
https://github.com/OCA/manufacture/pull/557

I would like to be sure that it can be generic before to end the PR

I also wait for a better module name ;-)

Thanks

**Comment by bealdav** [comment]
Hi @LoisRForgeFlow possible module names:

- mrp_production_request_qty_by_capacity
- mrp_request_qty
- mrp_request_qty_by_capacity
- ...

My favorite is the last one. I think the first is too long.

Any advice ?
