### ISSUE TITLE
RFC allow to trigger manufacturing orders of components from a mrp_manufacturing_request

### ISSUE THREAD

**Issue by bealdav** [OCA/manufacture#556]
Use case:

You define a manufacturing request. The attached bom implied let see to you need components available to make this production (the actual wizard has this feature).

An additional feature could be from this information, to trigger a MO to cover your need in components, maybe just a click.

In this case you'll get components availability before to create MO defined in manufacturing request. Then it lead to an easy driving of your production.

Please could you give me a feedback ?

@LoisRForgeFlow

**Comment by LoisRForgeFlow** [comment]
From my PoV to procure components from a MR feels like reinventing the wheel. I would rather create a MO from a MR for the desired qty (you can tweak how this qty is proposed based on you use case) and then let MRP recalculate your needs for components based on the already existing MO.

This is just my opinion, and without all the insights of your use case. If you think it would be helpful I will technically review the module with pleasure :)

**Comment by bealdav** [comment]
@LoisRForgeFlow Thanks a lot for your feedback. You're probably right, it's another way to do thing.
