### ISSUE TITLE
[12.0] quality_control

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/manufacture#562]
Hi,

I am testing the quality control module and I have a small problem.

Create a new test (QA> Tests> Tests)
Enter the name of the test: New test
Select the test type: related

Reference Object is Empty
![image](https://user-images.githubusercontent.com/3595132/100563859-39bf6c00-329e-11eb-9822-7f2b0d21d70c.png)

If you select blank values this error is displayed:
![image](https://user-images.githubusercontent.com/3595132/100563999-81de8e80-329e-11eb-92f5-58db7c0e165a.png)

**Comment by bodedra** [comment]
It seems issue at https://github.com/OCA/manufacture/blob/12.0/quality_control/models/qc_test.py#L26
