### ISSUE TITLE
[13.0] stock_picking_product_kit_helper: Error when access picking from purchase order

### ISSUE THREAD

**Issue by cramosh** [OCA/manufacture#564]
I install stock_picking_product_kit_helper in Odoo 13 community. 

When I create and validate a purchase order and attempt to access the delivery note. A error occurs. stock.picking (25,) Has_product_kit

I tested in ocarunbot and occurs same error. 

The error occurs in function  def _compute_has_product_kit(self)

I solved with the next code

    def _compute_has_product_kit(self):
        value = False
        for picking in self:
            if any(
                    picking._is_product_kit(line.product_id, line.company_id)
                    for line in picking.mapped("move_lines.sale_line_id")
            ):
                value = True
            picking.has_product_kit = value

![imagen](https://user-images.githubusercontent.com/34350771/100904276-26431980-34c7-11eb-934c-125e6778fac4.png)

**Comment by AaronHForgeFlow** [comment]
same error when creating a planned transfer from scratch on runbot:

![image](https://user-images.githubusercontent.com/19620251/117139265-53646280-adac-11eb-95f4-f7a4d36cbd62.png)
