### ISSUE TITLE
MRP_Subcontracting tests fail in 12.0

### ISSUE THREAD

**Issue by bealdav** [OCA/manufacture#581]
Tests test_flow_3 and test_flow_4 fail

![Selection_139](https://user-images.githubusercontent.com/1853434/103225435-30233580-492a-11eb-8abd-cb45facf6421.png)

Here is the fail
https://travis-ci.com/github/OCA/manufacture/jobs/464656901#L2240

![Selection_140](https://user-images.githubusercontent.com/1853434/103225647-b3dd2200-492a-11eb-935a-389a0db63cd9.png)

Could you help me @Tardo @pedrobaeza on this topic. I don't really understand how does it should works this.

That I can see is there is a component on Component2
https://github.com/OCA/manufacture/blob/12.0/mrp_subcontracting/tests/common.py#L51

Then why it needs to have a supplier on Component2 ?

The fail is not systematic. I observe it occur when you have these modules installed before:
mrp_stock_orderpoint_manual_procurement,quality_control,quality_control_stock,quality_control_team,mrp_progress_button,mrp_production_show_post_inventory,mrp_production_request,mrp_production_putaway_strategy,mrp_production_auto_post_inventory,mrp_bom_tracking,mrp_bom_note,mrp_bom_line_sequence,mrp_auto_create_lot,mrp_auto_assign,stock_picking_product_kit_helper,mrp_bom_component_menu,mrp_production_grouped_by_product,mrp_unbuild_tracked_raw_material,mrp_warehouse_calendar,product_mrp_info,product_quick_bom,quality_control_issue,quality_control_mrp,mrp_request_workcenter_cycle,account_move_line_manufacture_info,mrp_multi_level_estimate,mrp_sale_info,repair_refurbish

If there is only mrp_subcontracting, then tests are OK

![Selection_141](https://user-images.githubusercontent.com/1853434/103226478-82fdec80-492c-11eb-938a-332525853e4e.png)

**Comment by bealdav** [comment]
Thanks a lot Pedro ;-)

**Comment by pedrobaeza** [comment]
Not so fast. This is still failing. I didn't reproduce it in local, but I guessed that the problem was that one. I have to re-check.

**Comment by pedrobaeza** [comment]
There was other occurrence of the same "test data initialization". Changed as well and now it should be OK.

**Comment by bealdav** [comment]
Nice Pedro, now branch is fixed could you merge this PR.
https://github.com/OCA/manufacture/pull/558
Many attempts have been done. It should works now.

Thanks
