### ISSUE TITLE
[RFC][14.0][repair_stock_move] Stock moves in repair orders

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/manufacture#604]
Currently stock moves are only created when the repair order is finalized.
This is a big problem for companies wishing to provision the materials before the work is actually done, because the inventory system does not know that there's any demand for materials when the user adds components to the repair.

This module intends to solve this problem by creating stock moves for every repair.line, and keeping it updated as user makes changes to the repair lines.

The reservation will only take place when the user completes the repair, in which case the stock moves will be reserved and  consumed at the same time.

**Comment by marcelsavegnago** [comment]
Hello @JordiBForgeFlow 

I have this same demand. Do you already have any code started?

**Comment by marcelsavegnago** [comment]
Sorry ... I saw now that it was even merged in 14. https://github.com/OCA/manufacture/pull/613

**Comment by Steff-mwl** [comment]
Hi @JordiBForgeFlow 
This module is really an improvement to the repair module. A little frustration is that is doesn't create procurement and so doesn't trigger procurement rules either, especially regarding the parts.

In my use case, the technician cannot enter into the stock so he needs a picking order which the stock manager will process. Best is to define a dedicated location for the repair workshop. On repair order confirmation, creating a procurement to satisfy the needs would be perfect.

I really don't understand how to create those procurements in code but I though would be ok to share my use case.

**Comment by marcelsavegnago** [comment]
@Steff-mwl Yes, a picking would do well.
