### ISSUE TITLE
base_repair v12 and v13 :duplicated fields in form view

### ISSUE THREAD

**Issue by fgarcia-humanoide** [OCA/manufacture#617]
User and date fields appear twice in the form

**Comment by marcelsavegnago** [comment]
@fgarcia-humanoide Hello. It's not a mistake. The base_repair module is a merger of repair_calendar_view and other improvements. Therefore, it is recommended to uninstall the repair_calendar_view module. Soon I will propose the removal of it.

**Comment by marcelsavegnago** [comment]
@fgarcia-humanoide in v13 this is really a problem

https://github.com/OCA/manufacture/pull/623
