### ISSUE TITLE
mocalculate data on MO does not bring the product_UOM

### ISSUE THREAD

**Issue by anajuaristi** [OCA/manufacture#62]
Create a bill of materials with a product in KG
Go to manufacturing order
Calculate data
The assigned product UOM in "planned materials" is Unit, so it's wrong and it's causing this error:

Field(s) product_uom failed against a constraint: You try to move a product using a UoM that is not compatible with the UoM of the product moved. Please use an UoM in the same UoM category.

This issue was reported  by me and @ybofr on this PR but you said it was not related to new hooks. I think it is, since the error appairs with "calculate data" button.
https://github.com/OCA/manufacture/pull/57

@pedrobaeza @rafaelbn @oihane

**Comment by pedrobaeza** [comment]
And it's not related, @anajuaristi, as just checked by @oihane. Please don't add noise and wait if you have already allocated a person for checking, then wait for her results and report it with more data.

**Comment by oihane** [comment]
Tested in runbot __base_ database:
1. Install **mrp**: OK
2. Install **mrp_operations**: OK
3. Install **mrp_hook**: OK
4. Install **mrp_operations_extension**: OK

In each step I created a BoM and I added "Ice Cream" as component (it has 'kg' as UoM) and it worked OK
After I created a MO with the product of the BoM I've just created and pushed the button "Calculate Data" it also worked OK

So I think you are not doing correctly the tests.

**Comment by anajuaristi** [comment]
Ok. It could be it's not related exactly to that module but somehow, somewhere is happening. It's because of that i opened the issue. Just to not forget and try to solve it.

**Comment by pedrobaeza** [comment]
This is where it happens: https://github.com/OCA/manufacture/blob/8.0/mrp_bom_reference_selection/models/mrp_bom_line.py#L38

**Comment by LoisRForgeFlow** [comment]
Closing due to aging, please feel free to reopen.
