### ISSUE TITLE
Quality control configuration

### ISSUE THREAD

**Issue by htamouya** [OCA/manufacture#633]
Hello,

Could you please let me know how to configure a test to be automatically triggered on the quality_control module.

My goal is to be able to configure a quality check step after manufacturing.

Counting on your support

Thanks

**Comment by pedrobaeza** [comment]
Check quality_control_mrp. For further questions, please go to forums.

**Comment by htamouya** [comment]
Thanks for your feedback, I will check quality_control_mrp.

Regards
