### ISSUE TITLE
quality_control_mrp api.model

### ISSUE THREAD

**Issue by ejans** [OCA/manufacture#67]
function `action_produce` in `mrp_production.py` has **api.model** and uses _self_ as instance (for move in self.move_created_ids2) this loop never executes.

**Comment by pedrobaeza** [comment]
Thanks for reporting. Indeed there's an error due to a change in the approach. It has been fixed in https://github.com/OCA/manufacture/commit/09efe68d9cb7860286a8ab6157532ca3c838520d
