### ISSUE TITLE
[Question] mrp_account_analytic and mrp_analytic_cost

### ISSUE THREAD

**Issue by yostashiro** [OCA/manufacture#671]
https://github.com/OCA/manufacture/tree/14.0/mrp_account_analytic
https://github.com/OCA/manufacture/tree/14.0/mrp_analytic_cost

@dreispt These two modules look quite similar inside and I'm a bit confused about which one to seriously look at.  Could you please shed some light on how to judge which module to use and why the functions are duplicated?  I apologise for the noise if it's already been explained somewhere.

**Comment by dreispt** [comment]
Hello, `mrp_analytic_cost` is to be discontinued, and most of the code moved to `mrp_account_analytic`.
See notes here: https://github.com/OCA/manufacture/pull/664#issuecomment-906551659

I had the idea the code had been removed and a deprecation notice added to the README, but I see it is not the case.
I should fix that.
