### ISSUE TITLE
[14.0][MIG] quality_control_oca: causing runbot to fail 

### ISSUE THREAD

**Issue by BernatPForgeFlow** [OCA/manufacture#694]
I need to migrate **mrp_progress_button** but I find Runbot error related with **quality_control_oca** module:

https://github.com/OCA/manufacture/blob/14.0/quality_control_oca/models/qc_trigger_line.py#L30

@enriquemartin Could you please check the error?

**Comment by AaronHForgeFlow** [comment]
I am trying to fix this issue here: https://github.com/OCA/manufacture/pull/695

**Comment by AaronHForgeFlow** [comment]
The fix is merged so this can be closed
