### ISSUE TITLE
[BUG] quality_control: Quality manager cannot delete auto generated inspections

### ISSUE THREAD

**Issue by diggy128** [OCA/manufacture#845]
Quality manager cannot delete auto generated inspections

## Module

- quality_control
- quality_control_oca for Odoo => 13

## Describe the bug
A quality manager cannot delete inspections that were auto-generated by the system

## To Reproduce
**Affected versions**: 12.0, 13.0, 14.0, 15.0

1. Create any document that auto generates an inspection
2. Cancel / delete that document
3. Login as a user that is in the Quality Manager group
4. Try to delete the inspection

**Expected behavior**
A quality manager should be able to delete any object that has access to.
Model access gives him the permission but the unlink function is overridden to forbid deleting auto generated inspections.
This is important when a document is deleted because the quality inspection cannot be deleted!

**Comment by pedrobaeza** [comment]
What is the message/error?

**Comment by diggy128** [comment]
The error comes from the overrided unlink function in qc_inspection.py

```    
def unlink(self):
        for inspection in self:
            if inspection.auto_generated:
                raise exceptions.UserError(
                    _("You cannot remove an auto-generated inspection.")
...
```

**Comment by pedrobaeza** [comment]
That was put on purpose. What are the reasons to remove an auto-generated inspection?

**Comment by diggy128** [comment]
>  This is important when a document is deleted because the quality inspection cannot be deleted!

When deleting the object that created the inspection, that inspection cannot be deleted!

Eg. Would it make sense to NOT be able to delete an invoice (draft) that was generated from a sales order if that order is cancelled?

**Comment by pedrobaeza** [comment]
Is there a cascade unlinking? I don't think so. Anyways, then the possible path is:

- Add a mitigation of the constraint by context.
- Add such context on the unlinking of the object
- OR empty the references, but keep the inspection.

**Comment by diggy128** [comment]
>     * Add a mitigation of the constraint by context.
>     * Add such context on the unlinking of the object
That could work but it would mean we would have to take care to pass the necessary context from every object that is referenced in qc.inspection and is likely to be deleted!

>     * OR empty the references, but keep the inspection.
If the inspection is not done (aka success or failed) if doesn't make sense to keep the inspection since they will be cancelled inspections that were auto generated but no reference to the object that generated them.


To put put this in line:

1. Do you think that a quality manager should have the right to delete quality inspections (much like he has the right to create and to create and delete tests), auto-generated or not?
2. If the answer to the above is no, wouldn't it be better to allow root user to be able to delete such records (since root user should have "unlimited" power over the data) than restricting deletion in code?

**Comment by pedrobaeza** [comment]
> That could work but it would mean we would have to take care to pass the necessary context from every object that is referenced in qc.inspection and is likely to be deleted!

Yes, that's the idea. Or overwrite `base` module and do a generic method for this.

**Comment by diggy128** [comment]
Overriding `base` to override a behavior that is enforced only in ONE model seems overkill.

What about point 2 above?

In any case, I'll put together a PR and continue there.

Thanks for the response!

**Comment by pedrobaeza** [comment]
Well, adding such magic code that bypass the restriction for superuser is not usually the best idea. Let's see what others think.

**Comment by diggy128** [comment]
@OCA/manufacturing-maintainers 
Any opinions on this?
