### ISSUE TITLE
[BUG v.8] Miscalculate the cost of raw materials

### ISSUE THREAD

**Issue by JMODaERP** [OCA/manufacture#88]
Step 1 : Create a Bill of Materials.

Step 2 : We apply a route.

Step 3 : Define the relationship between the quantity to produce and the raw material.

![1 2016-02-03 10_06_42-odoo bill of material](https://cloud.githubusercontent.com/assets/15608043/12778244/0deae928-ca62-11e5-9a4c-8e1b96c594f2.jpg)

Step 4 : Make a production order.

Step 5 : We produce and finalize the order.

Step 6 : We look at the amount of raw material used in the order itself.

![2 2016-02-03 09_33_08-devel - manufacturing orders - odoo-consumed](https://cloud.githubusercontent.com/assets/15608043/12778265/273f1642-ca62-11e5-9e34-379cc2ae1e70.jpg)

Step 7 : analyze actual costs against estimated costs (Costs and Revenue).

BUG : Increases consumer unit

![4 2016-02-03 10_09_17-devel - costs revenues - odoo revenue vs costs](https://cloud.githubusercontent.com/assets/15608043/12778301/5bc592ec-ca62-11e5-82fb-07b4ea268e5a.jpg)

Current behavior:

 In the real Cost BUG : Increases consumer unit.

Expected Behavior: 

To calculate the actual cost ; multiplying the consumed amount of raw material by price, as it does when calculating the estimated cost.

Thanks.

**Comment by rafaelbn** [comment]
Hi  @ddico @pedrobaeza @anajuaristi, any idea about this bug?

**Comment by pedrobaeza** [comment]
I don't get what is the problem... Can you explain it clearer?

**Comment by JMODaERP** [comment]
Raw material consumed 0,21 see Consumed Products in the second visual.

Price 103,2.

The material real cost is 0,21 \* 103,20 = 21,22 more or less 21,67

**Comment by JMODaERP** [comment]
Hi Peter, what do you not understand?. 

The actual cost of the raw material consumed is calculated by multiplying 0.21 pieces for the price of the same provisions of 103.2 and that gives the € 21.22, approximately 21,67, that the estimated costs calculated as 103, 19 \* 0.21.

For that you can understand the process: 

With a polystyrene block 2 meters x 1.20 meters x 30 cms high and with a manufacture machine called a pantograph, we manufacture  1,800 small pieces of polystyrene using a fifth block, which is a cost would of 21 euros. The rest of the block is saved for other subsequent fabrications.

You see, in the third image, the estimated cost is perfectly calculated with the same BOM, so the system is able to get well from the BoM and the cost of production. 

What I do not understand is why the raw material consumed goes from 0.21 to 1 (by rounding not expected), thereby applying the 103.2 euros of cost of materials to small pieces that would thus losses ( without really giving them) they would be out of the market or if we sold on margin.

I hope you is sufficiently clear. Best regards.

**Comment by JMODaERP** [comment]
It is very important to have resolved this issue.

There fabrications for which the raw material is storable and is packaged in large blocks or pieces that many finished products are obtained. That is why if I need a fifth of a block of raw material to produce a given quantity of finished products should not apply the cost of acomplete piece products.

An example of this occurs in the automotion sector, with a large block of polystyrene (105 €) can be manufactured many components of the dashboard of a vehicle (8,900) whose total cost real unit of material would be €105 (€ 0.01179775. Unit).But if the manufacturer needs, at any given time, make 1800 units, the real cost of material should be € 21.2359551 and not at 105 €, since the factory has a machine that allows you to work effectively and raw material economy.

As we all know an MRP (systems MRP - Materials Requirement Planning-) is an important support with the MRPII (Manufacturing Resource Planning, for the companies in the industrial production sector achieve competitiveness in the market in which they operate. 

Therefore these companies acquire SW packages that help them save costs, so as a consultant should prescribe those SW to help them be more productive and as an analyst in Odoo I propose that the Open ERP provides for the functionality that solves the problem of production in any sector anywhere in the world. I beseech you to join me in this beautiful task and together make Odoo ERP the most effective tool in cost effectiveness ratio.

**Comment by JMODaERP** [comment]
![2016-02-14 18_06_57-solucionado 2016-02-14 18_06_16-costs revenues - odoo pr 91-b](https://cloud.githubusercontent.com/assets/15608043/13035053/446a1d1a-d346-11e5-817e-5e6948057f8a.jpg)

The PR https://github.com/OCA/manufacture/pull/91 not only imputes hrs hand but also fixes this issue. In the PR / 91 decimals are no longer rounded to the first integer unit, as this was happening BUG. :+1:

**Comment by JMODaERP** [comment]
# 8.0 mrp production real cost uptime update #91

**Comment by LoisRForgeFlow** [comment]
Fix has been merged. closing.
