### ISSUE TITLE
Machine history as a chatter

### ISSUE THREAD

**Issue by clonedagain** [OCA/manufacture#9]
As a complement to requirements 50-65 in https://docs.google.com/spreadsheets/d/1wfmiT5nAW7d9I4CAyNQ2IKdOLzpN1a0rnR6Q539lf6M/edit#gid=0, it would probably be useful to keep track of those changes in a chatter, so that interested users get be informed when a machine is out of order, moved, reconfigured...

**Comment by clonedagain** [comment]
@pedrobaeza @anajuaristi is this on your roadmap by any chance?

**Comment by anajuaristi** [comment]
Sorry, but machine status workflow it's not on our roadmap since our customers did not ask for it, neither the chatter on machines. 
Thank you:
Ana

**Comment by LoisRForgeFlow** [comment]
Closing as the requirement is not going to be fulfilled.
