### ISSUE TITLE
[14.0][mrp_subcontracting_partner_management] wrong routes configuration

### ISSUE THREAD

**Issue by dcorio** [OCA/manufacture#911]
Apologies in advance for the brevity :-)

The module doesn't create the rules needed by the "Resupply Subcontractor on Order" default route

**Comment by dcorio** [comment]
CC @francesco-ooops

**Comment by francesco-ooops** [comment]
@elvise what do you think?

**Comment by elvise** [comment]
> Apologies in advance for the brevity :-)
> 
> The module doesn't create the rules needed by the "Resupply Subcontractor on Order" default route

@dcorio thanks for your feedback :) 
Please tell me what's wrong

**Comment by elvise** [comment]
@dcorio Can we close this issue ? :)

**Comment by elvise** [comment]
@dcorio gentle reminder :)
