### ISSUE TITLE
[8.0][mrp_operations_extension] Doubt about number of operators

### ISSUE THREAD

**Issue by rubencr7** [OCA/manufacture#95]
Hi, I have the next doubt:
In production routing when it's selected the operation for copying his data in the workcenter lines, it is loading each line with respective data to each workcenter of that operation. On each line it is loading the number of operators of that operation through `onchange_operation()` in `MrpRoutingWorkcenter` class. It could be corrected as follows, and also take it from workcenter as the other fields, adding also the average cost of operator, that is not being loaded on the onchange:

```
data = {
    'default': is_default,
    'workcenter': operation_wc.id,
    'capacity_per_cycle': operation_wc.capacity_per_cycle,
    'time_efficiency': operation_wc.time_efficiency,
    'time_cycle': operation_wc.time_cycle,
    'time_start': operation_wc.time_start,
    'time_stop': operation_wc.time_stop,
    # vvvv Original vvvv
    # 'op_number': self.operation.op_number,
    # vvvv Proposal vvvv
    'op_number': operation_wc.op_number,
    'op_avg_cost': operation_wc.op_avg_cost,
}
```

Cheers!

**Comment by LoisRForgeFlow** [comment]
Closing due to aging, please feel free to reopen.
