### ISSUE TITLE
Missing Modules in V9

### ISSUE THREAD

**Issue by mmalorni** [OCA/manufacture#97]
Hi,
I noticed that a lot of modules that were present in v8 are not present in V9. Is there a reason why they have not been put in this new branch and gotten their installable property set to false?
#41 seem to have them all listed for upgrade to v9.

**Comment by pedrobaeza** [comment]
They have been introduced in the 8.0 branch after the fork to v9 (that it was done several months ago). The migration procedure includes how to handle this: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
