### ISSUE TITLE
[15] `mrp_bom_attribute_match` cannot handle nested BOMs

### ISSUE THREAD

**Issue by felixhummel** [OCA/manufacture#997]
Nested BOMs with product variants result in a traceback (see below).

## Module
`mrp_bom_attribute_match`

## Describe the bug
We're using product variants and nested BOMs with a hierarchy like this:

- top level product with two attributes
- sub level product with the same two attributes
- sub-sub level products with one attribute each

## To Reproduce
In version 15.

See the failing unit test here:
https://github.com/hukudo/oca-manufacture/blob/bug/997-mrp_bom_attribute_match-nested-boms/mrp_bom_attribute_match/tests/test_mrp_bom_attribute_match_nested.py

Or do the following steps:

Create a "Top-Level" product like this:
![image](https://user-images.githubusercontent.com/461438/223151289-701a2c21-1655-4f2b-aec1-ca1563d54db2.png)

Create a "Sub Level" product:
![image](https://user-images.githubusercontent.com/461438/223151381-b6a1a18d-e8f4-4a73-9983-44075bb3fd9e.png)

Create a "SubSub" product:
![image](https://user-images.githubusercontent.com/461438/223151456-d500b83a-983d-4254-a465-b7f8db40a202.png)

Create a "SubSub2" product:
![image](https://user-images.githubusercontent.com/461438/223151511-546f1caa-822e-464f-877c-1c37c5bc28c9.png)

Create a BOM "Sub Level":
![image](https://user-images.githubusercontent.com/461438/223151624-ca3006ec-5b90-4304-a555-b9edb4c6887e.png)

Note that its "Structure & Cost" works as expected.

Lastly create a BOM "Top Level":
![image](https://user-images.githubusercontent.com/461438/223151760-a8368ac3-5681-4c61-a94b-7be75deff976.png)

**Expected behavior**
"Structure & Cost" should show up and allow us to select the variant.

**Actual**
Traceback:
```
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/odoo/odoo/models.py", line 5213, in ensure_one
    _id, = self._ids
ValueError: not enough values to unpack (expected 1, got 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/odoo/odoo/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/odoo/odoo/http.py", line 916, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/odoo/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo/addons/web/controllers/main.py", line 1342, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/odoo/addons/web/controllers/main.py", line 1334, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/odoo/odoo/api.py", line 460, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/home/odoo/odoo/odoo/api.py", line 433, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/odoo/odoo/addons/mrp/report/mrp_report_bom_structure.py", line 44, in get_html
    res = self._get_report_data(bom_id=bom_id, searchQty=searchQty, searchVariant=searchVariant)
  File "/home/odoo/odoo/addons/mrp/report/mrp_report_bom_structure.py", line 97, in _get_report_data
    lines = self._get_bom(bom_id, product_id=searchVariant, line_qty=bom_quantity, level=1)
  File "/home/odoo/odoo/addons/mrp/report/mrp_report_bom_structure.py", line 143, in _get_bom
    components, total = self._get_bom_lines(bom, bom_quantity, product, line_id, level)
  File "/home/odoo/addons/mrp_bom_attribute_match/reports/mrp_report_bom_structure.py", line 34, in _get_bom_lines
    components, total = super()._get_bom_lines(
  File "/home/odoo/odoo/addons/mrp/report/mrp_report_bom_structure.py", line 166, in _get_bom_lines
    sub_total = self._get_price(line.child_bom_id, factor, line.product_id)
  File "/home/odoo/odoo/addons/mrp/report/mrp_report_bom_structure.py", line 260, in _get_price
    not_rounded_price = line.product_id.uom_id._compute_price(line.product_id.with_company(company).standard_price, line.product_uom_id) * prod_qty
  File "/home/odoo/odoo/addons/uom/models/uom_uom.py", line 234, in _compute_price
    self.ensure_one()
  File "/home/odoo/odoo/odoo/models.py", line 5216, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/odoo/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Expected singleton: uom.uom()
```

**Comment by lk-eska** [comment]
bug exists in 14.0 as well.

**Comment by francesco-ooops** [comment]
@ivantodorovich could you take a look?

**Comment by giarve** [comment]
I think the problem exists because only the parent BoM is created on the fly, but not its component BoMs. 
The cost function is recursive because it has to calculate the price for each component, and it fails when it reaches a BoM where the product_id is not set (because it has a dynamic component), and the hack has not been applied there.

Therefore, BoMs should be recursively created for each component using .new() on `mrp.bom.line` `child_bom_id` field.

Correct me if I'm wrong.

**Comment by lk-eska** [comment]
It requires a change in a method. Here's the fix:


from odoo import models

class ReportBomStructure(models.AbstractModel):
    _inherit = 'report.mrp.report_bom_structure'

    def _get_bom_lines(self, bom, bom_quantity, product, line_id, level):
        components = []
        total = 0
        for line in bom.bom_line_ids:
            line_quantity = (bom_quantity / (bom.product_qty or 1.0)) * line.product_qty
            if line._skip_bom_line(product):
                continue
            company = bom.company_id or self.env.company
            product_id = bom.get_component_template_product(
                line, product, line.product_id
            )
            price = product_id.uom_id._compute_price(product_id.with_company(company).standard_price,
                                                     line.product_uom_id) * line_quantity
            if line.child_bom_id:
                factor = line.product_uom_id._compute_quantity(line_quantity, line.child_bom_id.product_uom_id)
                sub_total = self._get_price(line.child_bom_id, factor, product_id)
            else:
                sub_total = price
            sub_total = self.env.company.currency_id.round(sub_total)
            components.append({
                'prod_id': product_id.id,
                'prod_name': product_id.display_name,
                'code': line.child_bom_id and line.child_bom_id.display_name or '',
                'prod_qty': line_quantity,
                'prod_uom': line.product_uom_id.name,
                'prod_cost': company.currency_id.round(price),
                'parent_id': bom.id,
                'line_id': line.id,
                'level': level or 0,
                'total': sub_total,
                'child_bom': line.child_bom_id.id,
                'phantom_bom': line.child_bom_id and line.child_bom_id.type == 'phantom' or False,
                'attachments': self.env['mrp.document'].search(['|', '&',
                    ('res_model', '=', 'product.product'),
                    ('res_id', '=', product_id.id), '&',
                    ('res_model', '=', 'product.template'),
                    ('res_id', '=', product_id.product_tmpl_id.id)]),

            })
            total += sub_total
        return components, total

**Comment by francesco-ooops** [comment]
@felixhummel porting #1100 to v15 should close this issue :)

**Comment by felixhummel** [comment]
Hi! Thanks for fixing this!
Sorry, for getting back to you this late, but somehow Github did not send notification emails to me.

@francesco-ooops Will this get ported to v15 automatically?
I'm new here, so please forgive my ignorance. :)

**Comment by francesco-ooops** [comment]
@felixhummel someone has to open the new PR, if you want to fw-port it please feel free to do it and we'll help you get it merged!
